[workspace]
members = [
    "projects/hello_cargo",
    "projects/guessing_game",
    "projects/common_programming_concepts"
    ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
