[package]
name = "packages_crates"
version = "0.1.0"
authors = ["Gavin Doughtie <gavin.doughtie@aon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
